# -*- coding: utf-8 -*-
"""lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19suScw2XSIbwQA1s8giFVvB6c8ab2b64
"""

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import pandas as pd
data=pd.read_csv("https://raw.githubusercontent.com/Deepsphere-AI/LVA-Batch4-Assessment/main/expenses.csv")
data

data.isnull().sum()

plt.figure(figsize=(10, 6))
sns.boxplot(data=data[['age', 'bmi', 'children', 'charges']])
plt.title('Boxplot for Outlier Detection')
plt.show()

Q1 = data.quantile(0.25)
Q3 = data.quantile(0.75)
IQR = Q3 - Q1

outliers = ((data < (Q1 - 1.5 * IQR)) | (data > (Q3 + 1.5 * IQR))).any(axis=1)

cleaned_df = data[~outliers]

cleaned_df

plt.figure(figsize=(10, 6))
sns.boxplot(data=cleaned_df[['age', 'bmi', 'children', 'charges']])
plt.title('Boxplot for Outlier Detection')
plt.show()

df = pd.get_dummies(cleaned_df, columns=['sex', 'smoker', 'region'], drop_first=True)
df

X = df.drop(columns=['charges'])
y = df['charges']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

age = float(input("Enter the age: "))
bmi = float(input("Enter the BMI: "))
children = int(input("Enter the number of children/dependents: "))
sex = int(input("Is the insured individual male? (1 for Yes, 0 for No): "))
smoker = int(input("Is the insured individual a smoker? (1 for Yes, 0 for No): "))
region_southeast = int(input("Is the insured individual from the Southeast region? (1 for Yes, 0 for No): "))
region_northwest = int(input("Is the insured individual from the Northwest region? (1 for Yes, 0 for No): "))
region_southwest = int(input("Is the insured individual from the Southwest region? (1 for Yes, 0 for No): "))
input_data = pd.DataFrame({
    'age': [age],
    'bmi': [bmi],
    'children': [children],
    'sex_male': [sex],
    'smoker_yes': [smoker],
    'region_northwest': [region_northwest],
    'region_southeast': [region_southeast],
    'region_southwest': [region_southwest]
})

predicted_charges = model.predict(input_data)
print("Predicted Insurance Charges:", predicted_charges[0])

from sklearn.metrics import r2_score

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

r_squared = r2_score(y_test, y_pred)
print("R-squared:", r_squared)

rmse = mean_squared_error(y_test, y_pred, squared=False)
print("Root Mean Squared Error (RMSE):", rmse)

