# -*- coding: utf-8 -*-
"""pythoninternal1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U4d2BnczFkkauwaYFVrrQm-ECbVp3baw
"""

#1
while True:
  length=int(input("enter length of the rectangle(in cm): "))
  width=int(input("enter breadth of the rectangle(in cm): "))
  area=length*width
  print("Area of the rectangle: ",area,"cm^2")

#2
while True:
  weight=int(input("enter weight(in kg): "))
  height=int(input("enter height(in cm): "))
  BMI=weight/((height/100)**2)
  print(BMI)

#3
student = {}

print('Enter student details')
while True:
    roll_number = int(input('Enter your 6 digit roll number: '))
    if roll_number in student:
        print('Roll Number Already Exists')
    else:
        name = input('Enter name: ')
        student[roll_number] = name
        print('Record added')
    ans = input('Do you want to continue(y/n)? ')
    if ans in 'nN':
        break

#4
while True:
  age=int(input("enter user's age: "))
  if age<18:
    print("Minor")
  if age>18 and age<45:
    print("Adult")
  else:
    print("Senior")

#5
for i in range(1,50):
  if i%2==0:
    print(i)

#6
password = "swa567"
pwd = input("Enter the password: ")
while pwd != password:
    print("Incorrect password. Try again.")
    pwd = input("Enter the password: ")
print("Granted!")

#7
def average(lst):
    return sum(lst) / len(lst)
lst = [34,555,43,22,7,0,765]
average = average(lst)
print("The average of the list is ",average)

#8
a = "Number of vowels in the String"
count = 0
i = 0

for i in range(len(a)):
    if (
        (a[i] == "a")
        or (a[i] == "e")
        or (a[i] == "i")
        or (a[i] == "o")
        or (a[i] == "u")
    ):
        count += 1

print("Number of vowels in the given string is: ", count)

#9
from datetime import datetime
a = datetime.now()
curr_time = a.strftime('%H:%M:%S')
print('Current Time is:', curr_time)
print('Current Date and Time is:', a)

#10
def get_numeric_input(prompt):

    while True:
        try:
            value = float(input(prompt))
            return value
        except ValueError:
            print("Error: Invalid input. Please Input a valid number.")
n1 = get_numeric_input("Input the first number: ")
n2 = get_numeric_input("Input the second number: ")
result = n1 * n2
print("Product of the said two numbers:", result)

#11
try:
    num = int(input("Enter an integer: "))
except ValueError:
    print("Invalid input. Please enter an integer.")

#12
try:
    num = 100
    den = 0
    result = num/den
    print(result)
except:
    print("Error: Denominator cannot be 0")

#13
f = open("myfile.txt", "w")
f.write("Hello,Python!\n")

#14
f= open("myfile.txt","r")
f.readlines()

#15

vFP_text_file = open('myfile.txt','w')
vLIST_word_list= []
for i in range (1, 5):
    print("Data to be written to file:: ")
    vAR_line = input()
    vLIST_word_list.append(vAR_line)
vFP_text_file.writelines(vLIST_word_list)
vFP_text_file.close()

